# Generated by Django 4.0.2 on 2022-02-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EssentialOils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('benefits', models.CharField(max_length=1000)),
                ('aromatic_description', models.CharField(max_length=1000)),
                ('photo_url', models.TextField()),
            ],
        ),
    ]
